site_name: Nekodocs
theme:
  name: material
nav:
  - Home: index.md
  - Cheatsheets: cheatsheets.md
  - C#:
    - dotnet: 
      - "Fix migrations": C#/dotnet/fix-manual-migrations.md
  - Docker: 
    - Swarm:
      - Dns: docker/swarm/dns.md
      - Volumes: docker/swarm/volumes.md
    - "API Connection": docker/api-connection.md
    - "API Docs": docker/api-docs.md
  - Go:
    - "Connect to docker API": go/connect-to-docker-api.md
    - "Format strings with fmt": go/format-strings-with-fmt.md
    - "Readers": go/readers.md
  - "Google cloud":
    - "Cloud storage":
      - "Tips for signed urls": "google-cloud/cloud-storage/signed-urls.md"
  - NodeJS:
    - NestJS:
      - "Inject repository example": node/nest/inject-repositories.md
  - Proxmox:
    - "Install r8168 network driver": proxmox/install-r8168-driver.md
  - YML:
    - Anchors: yml/anchors.md
    - Cheatsheet: yml/cheatsheet.md
