site_name: Nekodocs
theme:
  name: material
  palette:
    primary: cyan
    accent: indigo
  features:
    - navigation.tabs
    - navigation.tracking
nav:
  - Home: index.md
  - Cheatsheets: cheatsheets.md
  - Programming:
    - C#:
      - dotnet: 
        - "Fix migrations": programming/C#/dotnet/fix-manual-migrations.md
    - Go:
      - "Connect to docker API": programming/go/connect-to-docker-api.md
      - "Format strings with fmt": programming/go/format-strings-with-fmt.md
      - Readers: programming/go/readers.md
    - NodeJS:
      - NestJS:
        - "Inject repository example": programming/node/nest/inject-repositories.md
    - Python:
      - Snippets: programming/python/snippets.md
      - "File objects": programming/python/fileobjects.md
  - Docker: 
    - Swarm:
      - Dns: docker/swarm/dns.md
      - Volumes: docker/swarm/volumes.md
    - "API Connection": docker/api-connection.md
    - "API Docs": docker/api-docs.md
    - "Compose file docs": docker/compose-file-docs.md
  - DB:
    - Postgres:
      - Guidelines: "db/postgres/general.md"
    - Sqlite:
      - Python: db/sqlite/python.md
  - "UI design":
    - Colors:
      - Links: ui-design/color/links.md
  - "Google cloud":
    - "Cloud storage":
      - "Tips for signed urls": "google-cloud/cloud-storage/signed-urls.md"
  - Proxmox:
    - "Install r8168 network driver": proxmox/install-r8168-driver.md
  - YML:
    - Anchors: yml/anchors.md
    - Cheatsheet: yml/cheatsheet.md
